spring:
  application:
    name: crypto_info_svc

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

crypto:
  api_url: ${CRYPTO_API_URL}
  api_key: ${CRYPTO_API_KEY}
