spring:
  application:
    name: crypto_info_svc
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

server:
  port: 8080

logging:
  level:
    com.sahil.crypto.info: DEBUG
    org.springframework.web: DEBUG

crypto:
  api_url: ${CRYPTO_API_URL}
  api_key: ${CRYPTO_API_KEY}
